# Generated by Django 3.2.17 on 2024-01-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationdata',
            name='AdditionalInformation',
        ),
        migrations.AddField(
            model_name='compensationdata',
            name='Additional_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='JobTitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='compensationdata',
            name='Timestamp',
            field=models.DateField(null=True),
        ),
    ]
