# Generated by Django 3.2.17 on 2024-01-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_logs', '0002_auto_20240107_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationDataV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateField()),
                ('Employment_Type', models.CharField(max_length=255)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Company_Size_Employees', models.CharField(max_length=255)),
                ('Primary_Location_Country', models.CharField(max_length=255)),
                ('Primary_Location_City', models.CharField(max_length=255)),
                ('Industry_in_Company', models.CharField(max_length=255)),
                ('Public_or_Private_Company', models.CharField(max_length=255)),
                ('Years_Experience_in_Industry', models.CharField(max_length=255)),
                ('Years_of_Experience_in_Current_Company', models.CharField(max_length=255)),
                ('Job_Title_In_Company', models.CharField(max_length=255)),
                ('Job_Ladder', models.CharField(max_length=255)),
                ('Job_Level', models.CharField(max_length=255)),
                ('Required_Hours_Per_Week', models.CharField(max_length=255)),
                ('Actual_Hours_Per_Week', models.CharField(max_length=255)),
                ('Highest_Level_of_Formal_Education_Completed', models.CharField(max_length=255)),
                ('Total_Base_Salary_2018', models.FloatField()),
                ('Total_Bonus_2018', models.FloatField()),
                ('Total_Stock_Options_Equity_2018', models.FloatField()),
                ('Health_Insurance_Offered', models.CharField(max_length=255)),
                ('Annual_Vacation_Weeks', models.CharField(max_length=255)),
                ('Are_you_happy_at_your_current_position', models.CharField(max_length=255)),
                ('Do_you_plan_to_resign_in_the_next_12_months', models.CharField(max_length=255)),
                ('Thoughts_about_the_direction_of_your_industry', models.TextField()),
                ('Gender', models.CharField(max_length=255)),
                ('Top_Skills_for_Job_Growth', models.TextField()),
                ('Have_you_ever_done_a_bootcamp', models.CharField(max_length=255)),
            ],
        ),
    ]
